-- 1. Установите Arend, следуя инструкциям на странице:
-- https://arend-lang.github.io/documentation/getting-started/download
-- В IDEA можно просто импортировать данный проект

-- 2. Определите аналоги следующих функций на языке Haskell
{- Haskell:
   second :: Nat -> Nat -> Nat -> Nat
   second _ y _ = y

   apply :: (Nat -> Nat) -> Nat -> Nat
   apply f x = f x

   compose :: (Nat -> Nat) -> (Nat -> Nat) -> Nat -> Nat
   compose f g x = f (g x)

   flip :: (Nat -> Nat -> Nat) -> Nat -> Nat -> Nat
   flip f x y = f y x

   second' = flip (second 0)
-}

\func second (_ y _ : Nat): Nat => y

\func apply (f : Nat -> Nat) (x : Nat): Nat => f x

\func compose (f g : Nat -> Nat) (x : Nat) => f (g x)

\func flip (f : Nat -> Nat -> Nat) (x y : Nat): Nat => f y x

\func second' : Nat -> Nat -> Nat => flip (second 0)

-- 3. Расставьте приоритеты функций f1, f2, f3, f4, f5 и f6 так, чтобы функция test проходила тайпчекинг

\import lect01 \hiding (+, *)

\func f1 (x y : Nat) => x
\func f2 : Nat => 0
\func \infix 1 f3 (f : Nat -> Nat) (z : Nat) : Int => 0
\func f4 : Nat => 0
\func \infix 2 f5 => f1
\func f6 => f4

\func test => f1 f2 f3 f4 f5 f6

-- 4. Определите функцию if, аналогичную следующей функции:
{- Haskell:
   if :: Bool -> Bool -> Bool -> Bool
   if True t _ = t
   if False _ e = e
-}

\func if (p x y : Bool): Bool \elim p
  | true => x
  | false => y

-- 5. Определите || через if

\func \infixr 2 || (x y : Bool) : Bool => if x true y

-- 6. Определите возведение в степень и факториал для натуральных чисел

\open Nat \hiding (-, div) -- Здесь лежат + и *

\func \infixr 8 ^ (x y : Nat): Nat \elim y
  | zero => 1
  | suc n => (x ^ n) * x

\func fac (x : Nat): Nat \elim x
  | zero => 1
  | suc n => fac n * suc n

-- 7. Определите mod и gcd

\func mod (x y : Nat): Nat \elim y
  | zero => zero
  | n => eval x n (suc x)
  \where {
    \func eval (x y cnt : Nat): Nat \elim cnt
      | zero => zero
      | suc k => \case x < y \with {
        | true => x
        | false => eval (x - y) y k
      }
  }

\func gcd (x y : Nat): Nat \elim x, y
  | zero, _ => zero
  | _, zero => zero
  | x, y => eval x y (x + y)
  \where {
    \func eval (x y cnt : Nat): Nat \elim cnt
      | zero => zero
      | suc k => \case mod y x \with {
        | zero => x
        | y' => eval y' x k
      }
  }
