\import Data.Bool
\import Data.Or
\import Logic
\import hw01 (fac)
\import lect02 \hiding (Empty, absurd)

-- 1. Определите полиморфный tail для списков

\func tail {A : \Type} (l : List A): List A \elim l
  | nil => nil
  | cons _ t => t

-- 2. Реализуйте любой (but choose wisely) алгоритм сортировки. Функцию сравнения можно принимать в качестве аргумента

\func sort {A : \Type} (f : A -> A -> Bool) (l : List A): List A => pushAll f l (size l)
    \where {
      \func size {A : \Type} (l : List A): Nat \elim l
        | nil => 0
        | cons _ tail => suc (size tail)

      \func pushAll {A : \Type} (f : A -> A -> Bool) (l : List A) (cnt : Nat): List A \elim cnt
        | zero => l
        | suc n => pushAll f (pushToTail f nil l n) n

      \func max {A : \Type} (f : A -> A -> Bool) (a b : A): A => if (f a b) a b

      \func min {A : \Type} (f : A -> A -> Bool) (a b : A): A => if (f a b) b a

      \func pushToTail {A : \Type} (f : A -> A -> Bool) (h l : List A) (cnt : Nat): List A \elim l, cnt
        | cons fst (cons snd tail), suc n =>
          pushToTail f (cons (min f fst snd) h) (cons (max f fst snd) tail) n
        | l, _ => reverse h ++ l
    }

-- 3. Докажите ассоциативность && и ||

\func &&-assoc (x y z : Bool) : (x and y) and z = x and (y and z) \elim x
  | true => idp
  | false => idp

\func ||-assoc (x y z : Bool) : (x or y) or z = x or (y or z) \elim x
  | true => idp
  | false => idp

-- 4. Докажите, что fac 3 равно 6

\func fac3=6 : fac 3 = 6 => idp

-- 5. Докажите следующие пропозициональные тавтологии (можно решить любые 2 из 3 задач)

-- t1 : (P and Q -> R) -> P -> Q -> R
\func t1 {P Q R : \Type} (f : \Sigma P Q -> R) (p : P) (q : Q) : R => f (p, q)

-- t2 : (P -> R) -> (Q -> R) -> P or Q -> R
\func t2 {P Q R : \Type} (f : P -> R) (g : Q -> R) (h : Or P Q) : R \elim h
  | inl p => f p
  | inr q => g q

-- t3 : ((P -> Q -> R) -> P) -> (P -> R) -> R
\func t3 {P Q R : \Type} (f : (P -> Q -> R) -> P) (g : P -> R) : R =>
  g (f (\lam (p : P) (_ : Q) => g p))

-- 6. Сформулируйте и докажите следующие пропозициональные тавтологии (можно решить любые 2 из 3 задач)

-- t4 : (P -> Q -> R) -> P /\ Q -> R
\func t4 {P Q R : \Type} (f : P -> Q -> R) (s : \Sigma P Q) : R \elim s
  | (p, q) => f p q
-- t5 : (P or Q -> P /\ Q) -> (P -> Q) /\ (Q -> P)
\func t5 {P Q : \Type} (f : Or P Q -> \Sigma P Q) : \Sigma (P -> Q) (Q -> P) => (left f, right f)
  \where {
    \func left {P Q : \Type} (f : Or P Q -> \Sigma P Q) (p : P) : Q => \case f (inl p) \with {
      | (_, q) => q
    }
    \func right {P Q : \Type} (f : Or P Q -> \Sigma P Q) (q : Q) : P => \case f (inr q) \with {
      | (p, _) => p
    }
  }
-- t6 : ((((P -> Q) -> P) -> P) -> Q) -> Q

-- 7. Докажите следующие утверждения

-- s1 : Если для любого x : Nat верно P(x), то существует x : Nat для которого P(x) верно
\func s1 (P : Nat -> \Type) (h : \Pi (x : Nat) -> P x) : \Sigma (x : Nat) (P x) => (0, h 0)

-- s2 : Если не существует x : Nat такого, что верно P(x), то P(3) не верно
\func s2 (P : Nat -> \Type) (h : \Sigma (x : Nat) (P x) -> Empty) (v : P 3) : Empty => h (3, v)

-- 8. Сформулируйте и докажите следующие утверждения

-- s3 : Если для всех x : Nat верно, что P(x) влечет Q(x), и существует x : Nat для которого верно P(x),
-- то существует x : Nat для которого верно Q(x)
\func s3 (P Q : Nat -> \Type) (h : \Pi (x : Nat) -> P x -> Q x) (v : \Sigma (x : Nat) (P x)):
  \Sigma (x : Nat) (Q x) \elim v
  | (x, p) => (x, h x p)

-- s4 : Если для всех x : Nat либо не верно P(x), либо не верно Q(x), то P(3) влечет, что Q(3) не верно
\func s4 (P Q : Nat -> \Type) (h : \Pi (x : Nat) -> Or (P x -> Empty) (Q x -> Empty)) (p : P 3) (q : Q 3): Empty =>
  \case h 3 \with {
    | inl f => f p
    | inr g => g q
  }
